version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: warp-diag-checker
    binary: warp-diag-checker
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: warp-diag-checker
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: Formula
    homepage: https://github.com/peakefficiency/warp-diag-checker
    description: "Simple tool to check for known warp issues"
    repository:
      owner: peakefficiency
      name: homebrew-releases
    caveats: "More information here: https://github.com/peakefficiency/warp-diag-checker"

chocolateys:
  - name: warp-diag-checker
    owners: eprosimon
    authors: Peak Efficiency
    project_url: https://github.com/peakefficiency/warp-diag-checker
    icon_url: "https://raw.githubusercontent.com/peakefficiency/warp-diag-checker/main/assets/icon.png"
    license_url: https://github.com/peakefficiency/warp-diag-checker/blob/main/LICENSE
    package_source_url: https://github.com/peakefficiency/warp-diag-checker
    docs_url: https://github.com/peakefficiency/warp-diag-checker/blob/main/README.md
    bug_tracker_url: https://github.com/peakefficiency/warp-diag-checker/issues
    tags: "network diagnostics warp cloudflare"
    summary: Warp Diagnostics Checker
    description: |
      Warp Diagnostics Checker is a simple tool to check for known warp issues.
      It helps diagnose common problems and provides helpful information to resolve them.
    release_notes: "https://github.com/peakefficiency/warp-diag-checker/releases/tag/{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
# ... (other config sections)
