name: list-usage-gif

on:
 workflow_dispatch: 
 push:
    tags:
    - "*"
    paths:
      - 'list-usage.tape' # Trigger the workflow when this file changes

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install warp-diag-checker
        run: go install github.com/peakefficiency/warp-diag-checker@latest

      - uses: actions/checkout@v3
      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'list-usage.tape'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated list-usage GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: 'list-usage.gif' # Commit only the check-usage.gif file
