name: update-usage-gifs

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    paths:
      - '*.tape'

jobs:
  vhs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tape: ['list-usage.tape', 'dump-usage.tape', 'check-usage.tape', 'info-usage.tape']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install warp-diag-checker
        run: go install github.com/peakefficiency/warp-diag-checker@latest

      - name: Install VHS
        uses: charmbracelet/vhs-action@v1
        with:
          version: "latest"

      - name: Check VHS Installation
        run: |
          if ! command -v vhs &> /dev/null; then
            echo "VHS installation failed"
            exit 1
          fi
          vhs --version

      - name: Generate GIF from tape
        run: vhs ${{ matrix.tape }}
        continue-on-error: true

      - name: Pull latest changes from the main branch
        run: git pull origin main

      - name: Commit GIF
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated ${{ matrix.tape }} GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
